[project]
name = "blog"
version = "0.1.0"
description = "Blog"
readme = "README.md"
requires-python = "==3.11.10"
dependencies = [
    "matplotlib>=3.10.8",
    "polars>=1.37.1",
]

[tool.uv]
no-cache = true
